/* field_main SUPPORT */
/* charset=ISO8859-1 */
/* lang=C++20 */

/* subroutine to parse a line into fields */
/* version %I% last-modified %G% */


/* revision history:

	= 1998-05-01, David A­D­ Morano
	This code module was written in C language transcribed from
	a prior VAX assembly language version (written circa 1980
	perhaps).  This is why this looks so "ugly"!  This code
	comes from stuff dated back to almost the pre-dawn era of
	modern computer languages!  I wrote the original VAX assembly
	version also.  This code below was then written (transcribed)
	into C-language perhaps around 1993 or 1983 (at AT&T Bell
	Laboratories).

	= 2023-11-04, David A­D­ Morano
	I (finally) changed the code to initialize the default
	character terminator blocks using the C++14 'constexpr'
	keyword.  Previously, the character terminator blocks were
	generated by an external program and then copy-and-pasted
	into here. :-)  Yes, we have finally come a long way.  For
	the record, the 'constexpr' code limitations of C++11 were
	too restrictive to really comfortably do this type of
	initialization previously.

*/

/* Copyright © 1998,2023 David A­D­ Morano.  All rights reserved. */

/*******************************************************************************

	Name:
	field_get

	Description:
	This object parses lines of c-strings for 'fields'.
	Terminator characters are used to delineate fields.

	Synopsis:
	int field_get(field *fsbp,cchar *terms,cchar **fpp) noex

	Arguments:
	- address of return status block
	- address of terminator block

	Returns:
	>=0	length of field just parsed out
	<0	error or not-found (system-return)

	The return status block outputs are:
	- length remaining in string
	- address of reminaing string
	- len of substring
	- address of substring
	- terminator character


	Name:
	field_sharg

	Description:
	This object retrieves the next shell-like argument (if there
	is one).

	Synopsis:
	int field_sharg(field *fsbp,cchar *terms,char *fbuf,int flen) noex

	Arguments:
	fsbp		field status block pointer
	terms		bit array of terminating characters
	fbuf		buffer to store result
	flen		length of buffer to hold result

	Returns:
	>=0	length of field just parsed out
	<0	error or not-found (system-return)


	Notes:
	This is a classic, ported forward from the old VAX-11/780
	days.  This was translated from VAX assembly language.

	Note:
	This code was messy when it was assembly language.  And it
	is still messy to this very day (here in C-lnaguage).  I had
	to get this statement out as a sort of disclaimer.

*******************************************************************************/

#include	<envstandards.h>	/* MUST be first to configure */
#include	<climits>		/* <- for |UCHAR_MAX| + |CHAR_BIT| */
#include	<cstddef>		/* |nullptr_t| */
#include	<cstdlib>
#include	<cstdarg>
#include	<clanguage.h>
#include	<utypedefs.h>
#include	<utypealiases.h>
#include	<usysdefs.h>
#include	<usysrets.h>
#include	<ascii.h>
#include	<baops.h>
#include	<strop.h>
#include	<char.h>
#include	<mkchar.h>
#include	<fieldterminit.hh>
#include	<localmisc.h>

#include	"field.h"

import libutil ;

/* local defines */


/* imported namespaces */


/* local typedefs */


/* external subroutines */


/* external variables */


/* local structures */


/* forward references */


/* local variables */

constexpr fieldterminit		quotes("\"\'") ;
constexpr fieldterminit		doubles("\"$\\`") ;
constexpr fieldterminit		dterms("\r!#$%&,:;<=>") ;
constexpr fieldterminit		shterms(" #") ;


/* local inline-subroutines */

static inline bool istermorquote(cchar *terms,int ch) noex {
	return (batst(terms,ch) || batst(quotes.terms,ch)) ;
}

static inline bool istermandnotquote(cchar *terms,int ch) noex {
	return batst(terms,ch) && (! batst(quotes.terms,ch)) ;
}

static inline bool isquoteanddouble(int sl,int ch) noex {
	return ((ch == CH_SQUOTE) && (sl > 1) && batst(doubles.terms,ch)) ;
}


/* exported variables */


/* exported subroutines */

int field_start(field *fsbp,cchar *lp,int ll) noex {
	int		rs = SR_FAULT ;
	if (fsbp && lp) {
	    rs = SR_OK ;
	    fsbp->fp = nullptr ;
	    fsbp->fl = 0 ;
	    fsbp->term = '\0' ;
	    if (ll < 0) ll = lenstr(lp) ;
	    while ((ll > 0) && char_iswhite(*lp)) {
	        lp += 1 ;
	        ll -= 1 ;
	    } /* end while */
	    if (*lp == '\0') ll = 0 ;
	    fsbp->lp = lp ;
	    fsbp->ll = ll ;
	} /* end if (non-null) */
	return (rs >= 0) ? ll : rs ;
}
/* end subroutine (field_start) */

int field_finish(field *fsbp) noex {
	int		rs = SR_FAULT ;
	if (fsbp) {
	    rs = SR_NOTOPEN ;
	    if (fsbp->lp) {
		rs = SR_OK ;
		fsbp->lp = nullptr ;
		fsbp->ll = 0 ;
	    } /* end if (open) */
	} /* end if (non-null) */
	return rs ;
}
/* end subroutine (field_finish) */

int field_get(field *fsbp,cchar *terms,cchar **fpp) noex {
	int		rs = SR_FAULT ;
	int		rs1 ;
	int		fl = 0 ; /* return-value */
	cchar		*fp = nullptr ;
	if (fsbp && fpp) {
	    if (terms == nullptr) terms = dterms.terms ;
	    if (strop so ; (rs = so.start(fsbp->lp,fsbp->ll)) > 0) {
		int	chterm = '\0' ;
		so.white() ;
		fp = so.sp ;	/* <- first field? */
	        if (so.sl > 0) {
	            int		ch = mkchar(*so.sp) ;
	            if (batst(quotes.terms,ch)) {
	                cint	qe = ch ;	/* set default quote end */
			so.inc() ;
	        	fp = so.sp ; 		/* save field address */
			so.findchr(qe) ;
	        	fl = intconv(so.sp - fp) ;
			so.inc() ;
	    	    } else if (! batst(terms,ch)) {
	        	fp = so.sp ;		/* save field address */
			so.inc() ;
	        	while (so.sl > 0) {
	            	    ch = mkchar(*so.sp) ;
	            	    if (istermorquote(terms,ch)) break ;
			    if (char_iswhite(ch)) break ;
			    so.inc() ;
	        	} /* end while */
	        	fl = intconv(so.sp - fp) ;
		    } /* end if (processing a field) */
	    	    if ((so.sl > 0) && char_iswhite(*so.sp)) {
	                chterm = ' ' ;
			so.white() ;
	            } /* end if */
	            ch = mkchar(*so.sp) ;
	            if ((so.sl > 0) && istermandnotquote(terms,ch)) {
	                chterm = ch ;
			so.inc() ;
	            } /* end if */
		} else {
		    fl = SR_NOTFOUND ;
	        } /* end if (positive) */
		fsbp->ll = so.sl ;
		fsbp->lp = so.sp ;
		fsbp->fl = fl ;
		fsbp->fp = (fl >= 0) ? fp : nullptr ;
		fsbp->term = chterm ;
		*fpp = fsbp->fp ;
		rs1 = so.finish ;
		if (rs >= 0) rs = rs1 ;
	    } /* end if (strop) */
	} /* end if (non-null) */
	return (rs >= 0) ? fl : rs ;
}
/* end subroutine (field_get) */

int field_getterm(field *fsbp,cchar *terms,cchar **fpp) noex {
	int		rs = SR_FAULT ;
	int		rs1 ;
	int		fl = 0 ; /* return-value */
	cchar		*fp = nullptr ;
	if (fsbp && fpp) {
	    if (terms == nullptr) terms = dterms.terms ;
	    if (strop so ; (rs = so.start(fsbp->lp,fsbp->ll)) > 0) {
		int	chterm = '\0' ;
		so.white() ;
		fp = so.sp ;	/* <- first field? */
	        if (so.sl > 0) {
	            int		ch = mkchar(*so.sp) ;
	            if (! batst(terms,ch)) {
	        	fp = so.sp ; 		/* save field address */
			so.inc() ;
			so.findterm(terms) ;
	        	fl = intconv(so.sp - fp) ;
	            } /* end if (processing a field) */
	            ch = mkchar(*so.sp) ;
	            if ((so.sl > 0) && batst(terms,ch)) {
	        	chterm = ch ;
			so.inc() ;
	            } /* end if */
		} else {
		    fl = SR_NOTFOUND ;
	        } /* end if (positive) */
	        fsbp->ll = so.sl ;
	        fsbp->lp = so.sp ;
	        fsbp->fl = fl ;
	        fsbp->fp = (fl >= 0) ? fp : nullptr ;
	        fsbp->term = chterm ;
	        *fpp = fsbp->fp ;
		rs1 = so.finish ;
		if (rs >= 0) rs = rs1 ;
	    } /* end if (so) */
	} /* end if (non-null) */
	return (rs >= 0) ? fl : rs ;
}
/* end subroutine (field_getterm) */

int field_sharg(field *fsbp,cchar *terms,char *fbuf,int flen) noex {
	int		rs = SR_FAULT ;
	int		rs1 ;
	int		fl = 0 ; /* return-value */
	if (fsbp && fbuf) {
	    if (terms == nullptr) terms = dterms.terms ;
	    if (strop so ; (rs = so.start(fsbp->lp,fsbp->ll)) > 0) {
		int	chterm = '\0' ;
		so.white() ;
	        if (so.sl > 0) {
		    int		ch ; /* used in two blocks below */
		    char	*bp = fbuf ;
	            while (so.sl > 0) {
		        int	qe ; /* used in two blocks below */
	                ch = mkchar(*so.sp) ;
		        if (istermandnotquote(terms,ch)) break ;
	                if (char_iswhite(ch)) break ;
	                if (ch == CH_DQUOTE) {
	                    qe = ch ;
		            so.inc() ;
	                    while (so.sl > 0) {
			        int	nch = 0 ;
	                        ch = mkchar(*so.sp) ;
	                        if (so.sl > 1) nch = mkchar(so.sp[1]) ;
			        if (isquoteanddouble(so.sl,nch)) {
			            so.inc() ;
	                            ch = mkchar(*so.sp) ;
	                            if (flen > 0) {
	                                *bp++ = charconv(ch) ;
	                                flen -= 1 ;
	                            }
			            so.inc() ;
	                        } else if (ch == qe) {
			            so.inc() ;
	                            break ;
	                        } else {
	                            if (flen > 0) {
	                                *bp++ = charconv(ch) ;
	                                flen -= 1 ;
	                            }
			            so.inc() ;
	                        } /* end if */
	                    } /* end while (processing the quoted portion) */
	                } else if (ch == CH_SQUOTE) {
	                    qe = ch ;
		            so.inc() ;
	                    while (so.sl > 0) {
	                        ch = mkchar(*so.sp) ;
	                        if (ch == qe) {
			            so.inc() ;
	                            break ;
	                        } else {
	                            if (flen > 0) {
	                                *bp++ = charconv(ch) ;
	                                flen -= 1 ;
	                            }
			            so.inc() ;
	                        } /* end if */
	                    } /* end while (processing the quoted portion) */
	                } else if ((ch == CH_SQUOTE) && (so.sl > 1)) {
		            so.inc() ;
	                    ch = mkchar(*so.sp) ;
	                    if (flen > 0) {
	                        *bp++ = charconv(ch) ;
	                        flen -= 1 ;
	                    }
			    so.inc() ;
	                } else {
	                    if (flen > 0) {
	                        *bp++ = charconv(ch) ;
	                        flen -= 1 ;
	                    }
			    so.inc() ;
	                } /* end if */
	            } /* end while (main loop) */
		    so.white() ;
	            if (so.sl > 0) {
	                chterm = ' ' ;
	                ch = mkchar(*so.sp) ;
		        if (istermandnotquote(terms,ch)) {
	                    chterm = ch ;	/* save terminator */
		            so.inc() ;
	                } /* end if */
	            } /* end if (positive) */
	            fl = intconv(bp - fbuf) ;
	            *bp = '\0' ;
	        } else {
		    fl = SR_NOTFOUND ;
	        } /* end if (positive) */
	        fsbp->ll = so.sl ;
	        fsbp->lp = so.sp ;
	        fsbp->fl = fl ;
	        fsbp->fp = fbuf ;
	        fsbp->term = chterm ;
		rs1 = so.finish ;
		if (rs >= 0) rs = rs1 ;
	    } /* end if (so) */
	} /* end if (non-null) */
	return (rs >= 0) ? fl : rs ;
}
/* end subroutine (field_sharg) */

int field_remaining(field *fsbp,cchar **lpp) noex {
	int		rs = SR_FAULT ;
	int		ll = 0 ; /* return-value */
	if (fsbp) {
	    rs = SR_NOTOPEN ;
	    if (fsbp->lp) {
		rs = SR_OK ;
		ll = fsbp->ll ;
	        if (lpp) {
	            *lpp = fsbp->lp ;
	        }
	    } /* end if (open) */
	} /* end if (non-null) */
	return (rs >= 0) ? ll : rs ;
}
/* end subroutine (field_remaining) */


