#!/usr/extra/bin/ksh
# SYNCMAKES
files_d | while read D ; do
  MF=${D}/Makefile
  if [[ -f $MF ]] ; then
    DN=${D%/*}
    BN=${D##*/}
    MFA=${BN}.mak
    if [[ -f $MFA ]] ; then
      if [[ $MF -ef $MFA ]] ; then 
        print -- YES
      else
        print -- NO $BN
        li $MF
        li $MFA
	ln -f $MF $MFA
      fi
    else
      print -- NOT present $MFA
      ln -f $MF $MFA
    fi
  fi
done

