#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} getourhe"


DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep "${N}" $F > ${DN} ; then
      ed - $F <<\EOF
g/getourhe/s//getheour/g
	w
	q
EOF
      fi
    done
  fi
done


