#!/usr/extra/bin/ksh
# CHANGEUNIX

NAMES=
NAMES="${NAMES} UNIX "


DN=/dev/null


for F in "${@}" ; do

  if [[ -r "${F}" ]] ; then

    for N in ${NAMES} ; do

      if fgrep ${N} $F > ${DN} ; then

      ed - $F <<\EOF
g/UNIX/s//UNIX®/g
g/UNIX®®/s//UNIX®/g
	w
	q
EOF

      fi

    done

  fi

done


