#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} mkpath2"

DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep -q "${N}" $F > ${DN} ; then
      ed - $F <<\EOF
g/mkpath2/s//mkpath/g
	w
	q
EOF
      fi
    done
  fi
done


