#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} limits.h errno.h signal.h stddef.h stdlib.h stdio.h string.h"
NAMES="${NAMES} stdarg.h"


DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep ${N} $F > ${DN} ; then
      ed - $F <<\EOF
g/limits.h/s//climits/g
g/errno.h/s//cerrno/g
g/signal.h/s//csignal/g
g/stddef.h/s//cstdef/g
g/stdlib.h/s//cstdlib/g
g/stdio.h/s//cstdio/g
g/stdarg.h/s//cstdarg/g
	w
	q
EOF
      fi
    done
  fi
done


