#!/usr/extra/bin/ksh
# MAKEMODULES
PN=${0##*/}
GCM=gcm.cache

function makeobj {
  typeset M=${1}
  MFO=${M}.o
  if havefile ${M}_*.c* || havefile ${M}[0-9]*.c* ; then
    MFO=${M}0.o
  fi
}

function makeone {
  MFO=
  if [[ -r "${M}.mod" ]] ; then
    MF=${M}.mod
  elif [[ -r "${M}.ccm" ]] ; then
    MF=${M}.mod
  fi
  makeobj ${M}
  if [[ ${MF} -nt ${GCM}/${M}.gcm ]] || [[ ${MF} -nt "${MFO}" ]] ; then
    if [[ -r ${M}.mod ]] ; then
      gxx -x c++ -c -O ${M}.mod
    elif [[ -r ${M}.ccm ]] ; then
      gxx -x c++ -c -O ${M}.ccm
    fi
    if [[ -r ${M}.o ]] ; then
      if havefile ${M}_*.c* || havefile ${M}[0-9]*.c* ; then
	mv -f ${M}.o ${M}0.o
      fi
    fi
  fi
}

for M in "${@}" ; do
  if [[ -r "${M}.mod" ]] || [[ -r "${M}.ccm" ]] ; then
    makeone $M
  else
    print -u 2 -- "${PN}: module -${M}- not found"
  fi
done

