#!/usr/extra/bin/ksh
# STOREDIGITHAND

CAN=digithandling
FILEGLOB=
FILEGLOB+=" cfx ctx "
FILEGLOB+=" digbufsizes.[ch]* "

CADIR=${HOME}/store/src
CAFILE=${CADIR}/${CAN}.ca.bz2

: ${TMPDIR:=/tmp}

PN=${0##*/}
TEF=${TMPDIR}/storedigithand${$}
if [[ -d ${CADIR} ]] ; then
  find ${FILEGLOB}  -type f -print | gcpio -oc 2> ${TEF} | bzip2 > ${CAFILE}
  print -u2 -- "${PN}: $( < ${TEF} )"
  rm -f ${TEF}
else
  print -u2 -- "${PN}: store directory not present"
fi
sync &

