#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} DATER_ZNAMESIZE "


DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep ${N} $F > ${DN} ; then
      ed - $F <<\EOF
g/DATER_ZNAMESIZE/s//DATER_ZNAMELEN/g
	w
	q
EOF
      fi
    done
  fi
done


