#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} VECHAND_P "


DN=/dev/null
builtin fgrep 2> ${DN}


for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep ${N} $F > ${DN} ; then
      ed - $F <<\EOF
g/VECHAND_P/s//VECHAND_O/g
	w
	q
EOF
      fi
    done
  fi
done


