#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} TRUE"


DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep ${N} $F > ${DN} ; then
      ed - $F <<\EOF
g/TRUE/s//true/g
	w
	q
EOF
      fi
    done
  fi
done


