#!/usr/extra/bin/ksh
# SYNCMAKES
files_d | while read D ; do
  find $D -type f -mtime -120 -name Makefile -print | while read N ; do
    BN=${N##*/}
    DN=${N%/*}
    if [[ -f ${IN} ]] ; then
      if [[ $N -ef ${IN} ]] ; then 
        print -- YES
      else
        print -- NO 
        li $N $IN
        ln -f $N include
      fi
    else 
      p -- "linking to INCLUDE ${N}"
      ln $N $IN
    fi
  done
done

