#!/usr/extra/bin/ksh
# GNU Compiler Collection
PN=${0##*/}
RF_OK=true
: ${INCDIR:=inc}
INCDIRS=
INCS="inc include"
if [[ ! -d ${INCDIR} ]] ; then
  for INC in ${INCS} ; do
    if [[ -d ${INC} ]] ; then
      INCDIR=${INC}
      break
    fi
  done
  if [[ ! -d ${INCDIR} ]] ; then
    if [[ -n "${REPOROOT}" ]] && [[ -d "${REPOROOT}" ]] ; then
      A=${REPOROOT}/include
      if [[ -d "${A}" ]] ; then
        INCDIR=${A}
      fi
    fi
  fi
fi
if [[ -n "${INCDIR}" ]] && [[ -d "${INCDIR}" ]] ; then
  INCDIRS="-I${INCDIR}"
fi
# execution-character-set option
EOPT=
if [[ -n "${LANG}" ]] ; then
  EOPT="-finput-charset=${LANG##*.} -fexec-charset=${LANG##*.}"
fi
# program
PROG="print -u2 -- ${PN}: no-program"
if ${RF_OK} ; then
  POPT="-pthread"
  COPT=
  MOPT="-fmodules-ts -Wno-global-module"
  OPTS=
  case ${PN} in
  gcpp*)
    PROG=gcpp14
    OPTS="${EOPT} ${INCDIRS}"
    ;;
  gcc*)
    PROG=gcc14
    OPTS="${EOPT} ${POPT} ${COPT} ${INCDIRS}"
    ;;
  gpp*|gxx*)
    PROG=gxx14
    OPTS="${EOPT} ${POPT} ${COPT} ${MOPT} ${INCDIRS}"
    ;;
  gld*)
    PROG=gld14
    OPTS="${POPT}"
    ;;
  granlib*)
    PROG=granlib14
    ;;
  gar*)
    PROG=gar14
    ;;
  gnm) 
     PROG=gnm14 
    ;;
  gnmd)
    PROG=gnm14
    OPTS="--demangle"
    ;;
  gcov*)
    PROG=gcov14
    ;;
  gsize*|gsz*)
    PROG=size
    ;;
  esac
  ${PROG} ${OPTS} "${@}"
fi

