#!/usr/extra/bin/ksh
# MAKEIT

: ${REPOROOT:=${HOME}/github/system}
export REPOROOT

BUILDTYPE=develope
#BUILDTYPE=deliver


: ${ARCHITECTURE:=$( architecture )}
: ${SYSNAME:=$( uname -s )}
: ${RELEASE:=$( uname -r )}
export ARCHITECTURE SYSNAME RELEASE 

: ${OSNAME:=${SYSNAME}}
: ${OSTYPE:=$( systype )}
: ${OSRELEASE:=${RELEASE}}
: ${OSNUM:=${RELEASE%%.*}}
export OSNAME OSTYPE OSRELEASE OSNUM


: ${CGS_BINDIR:=${REPOROOT}/bin}
: ${CGS_INCDIR:=${REPOROOT}/include}
: ${CGS_LIBDIR:=${REPOROOT}/lib}
: ${CGS_MANDIR:=${REPOROOT}/man}

: ${CGS_CRTDIR:=${USRLOCAL}/lib}
: ${CGS_VALDIR:=${USRLOCAL}/lib}
: ${CGS_RUNDIR:=${USRLOCAL}/lib}

: ${CGS_INFODIR:=${REPOROOT}/info}
: ${CGS_HELPDIR:=${REPOROOT}/share/help}
: ${CGS_LDRPATH:=${REPOROOT}/lib}

: ${CGS_CPP:=cpp}
: ${CGS_CC:=clang}
: ${CGS_CXX:=clang++}
: ${CGS_LD:=ld}
: ${CGS_RANLIB:=ranlib}
: ${CGS_AR:=ar}
: ${CGS_NM:=nm}
: ${CGS_COV:=cov}
: ${CGS_SZ:=sz}

: ${CGS_GCPP:=gcpp}
: ${CGS_GCC:=gcc}
: ${CGS_GPP:=gpp}
: ${CGS_GLD:=gld}
: ${CGS_GRANLIB:=granlib}
: ${CGS_GAR:=gar}
: ${CGS_GNM:=gnm}
: ${CGS_GCOV:=gcov}
: ${CGS_GSZ:=gsz}

export CGS_BINDIR
export CGS_INCDIR
export CGS_CRTDIR
export CGS_VALDIR
export CGS_LIBDIR
export CGS_MANDIR
export CGS_RUNDIR

export CGS_INFODIR
export CGS_HELPDIR
export CGS_LDRPATH

export CGS_CPP
export CGS_CC
export CGS_CXX
export CGS_LD
export CGS_RANLIB
export CGS_AR
export CGS_NM
export CGS_SZ

export CGS_GCPP
export CGS_GCC
export CGS_GPP
export CGS_GLD
export CGS_GAR
export CGS_GNM
export CGS_GRANLIB
export CGS_GCOV
export CGS_GSZ


function getflags {
  typeset A DN=/dev/null FL=${1}
  if [[ -n "${FL}" ]] ; then
    A="$( getconf ${1} 2> ${DN} )"
    if [[ "${A}" != 'undefined' ]] && [[ "${A}" != 'error' ]] ; then
      print -- "${A}"
    fi
  fi
}

case ${OSNAME}:${OSNUM} in
Darwin:*)
  : ${CO_GCCALL:=""}
  : ${CO_GCCDEB:="-Wall -Wextra"}
  : ${CO_GCCOPT:=""}
  : ${CO_GCCLIB:="-fpic"}
  : ${CO_GPPALL:=""}
  : ${CO_GPPDEB:="-Wall -Wextra"}
  : ${CO_GPPOPT:=""}
  : ${CO_GPPLIB:="-fpic"}
  case ${BUILDTYPE} in
  debug)
    CO_GCCOPT="-g"
    CO_GPPOPT="-g"
    ;;
  deliver)
    CO_GCCOPT="-O"
    CO_GPPOPT="-O"
    ;;
  esac
  ;;
SunOS:*)
  : ${CO_GCCALL:=""}
  case "${ARCHITECTURE}" in
  sparc)
    CO_GCOPARC="-mcpu=v9"
    CO_GCCLIBSPARC="-mno-app-regs "
    : ${CO_GCCOPT:="-O3 ${CO_GCOPARC}"}
    : ${CO_GCCLIB:="-fpic ${CO_GCCLIBSPARC}"}
    ;;
  *)
    : ${CO_GCCOPT:="-O3"}
    : ${CO_GCCLIB:="-fpic"}
    ;;
  esac
  : ${CO_GCCOPT:="-O3"}
  : ${CO_GCCLIB:="-fpic"}
  : ${CO_CCALL:="-MT"}
  : ${CO_CCOPT:="-O"}
  : ${CO_CCLIB:="-Kpic"}
  ;;
esac

export CO_CCALL 
export CO_CCDEB
export CO_CCOPT 
export CO_CCLIB

export CO_CXXALL 
export CO_CXXDEB
export CO_CXXOPT 
export CO_CXXLIB

export CO_GCCALL 
export CO_GCCDEB
export CO_GCCOPT
export CO_GCCLIB

export CO_GPPALL 
export CO_GPPDEB
export CO_GPPOPT
export CO_GPPLIB


export BINDIR=${REPOROOT}/bin
export INCDIR=${REPOROOT}/include
export LIBDIR=${REPOROOT}/lib
export MANDIR=${REPOROOT}/man
export INFODIR=${REPOROOT}/info
export HELPDIR=${REPOROOT}/share/help
export CRTDIR=${CGS_CRTDIR}
export VALDIR=${CGS_VALDIR}
export RUNDIR=${CGS_RUNDIR}


export CPP=${CGS_GCPP}
export CC=${CGS_GCC}
export CXX=${CGS_GPP}
export LD=${CGS_GLD}
export AR=${CGS_GAR}
export NM=${CGS_GNM}
export RANLIB=${CGS_GRANLIB}
export COV=${CGS_GCOV}
export SZ=${CGS_GSZ}
export LORDER="lorder"
export TSORT="tsort"
export LINT="lint"
export RM="rm -f"
export TOUCH="touch"
export LINT="lint"


# compiler and flags seletion for MAKE
CFLAGS=
CXXFLAGS=

case ${BUILDTYPE} in
develope|debug)
  MAKECPPFLAGS=
  MAKECFLAGS="${CO_GCCALL} ${CO_GCCDEB} ${CO_GCCOPT} ${CO_GCCLIB}"
  MAKECXXFLAGS="${CO_GPPALL} ${CO_GPPDEB} ${CO_GPPOPT} ${CO_GPPLIB}"
  MAKELDFLAGS=
  ;;
test)
  ;;
analyze)
  ;;
profile)
  ;;
deliver)
  MAKECPPFLAGS=
  MAKECFLAGS="${CO_GCCALL} ${CO_GCCOPT} ${CO_GCCLIB}"
  MAKECXXFLAGS="${CO_GPPALL} ${CO_GPPOPT} ${CO_GPPLIB}"
  MAKELDFLAGS=
  MAKELDFLAGS=
  ;;
esac

export BUILDTYPE
export MAKECPPFLAGS
export MAKECFLAGS
export MAKECXXFLAGS
export MAKELDFLAGS


#print -- CGS_CC=${CGS_CC}
#print -- CGS_GPP=${CGS_GPP}
#print -- REPOROOT=${REPOROOT}

export PATH=${REPOROOT}/bin:${PATH}
make "${@}"


