#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} offset_t "


DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep ${N} $F > ${DN} ; then
      ed - $F <<\EOF
g/offset_t/s//off_t/g
	w
	q
EOF
      fi
    done
  fi
done


