#!/usr/extra/bin/ksh
# RMDB

: ${EXTRA:=/usr/extra}
: ${USRLOCAL:=/usr/local}
: ${LOCAL:=/opt/local}
: ${GNU:=/opt/gnu}
: ${NCMP:=/opt/ncmp}
: ${PCS:=/opt/pcs}
: ${AST:=/opt/ast}

: ${LANG:="en_US.ISO8859-1"}
: ${HOME:=$( ${LOCAL}/bin/userhome )}


PRS="${EXTRA} ${LOCAL}"

for PR in ${PRS} ; do
  VDIR=${PR}/var/bvses
  if [[ -d ${VDIR} ]] ; then
    rm -f ${VDIR}/*.bvs* &
  fi
done
wait


