#!/usr/extra/bin/ksh
# MKLINKS

CMDS=" haveprogram havefunction pathto fpathto pathenum "
LOCPROG=macuser.x

function linkdir {
  typeset TDIR=${1}
  for C in ${CMDS} ; do
    ln -f ${LOCPROG} ${TDIR}/bin/${C}
  done
}

if [[ -x "${LOCPROG}" ]] ; then
  for D in /usr/local /opt/local ; do
    if [[ -d "${D}" ]] ; then
      linkdir $D
    else
      print -u 2 -- "target directory not present"
      break ;
    fi
  done
else
  print -u 2 -- "program not made"
fi


