#!/usr/extra/bin/ksh
# MKLINKS

CMDS=" username userhome usershell "
CMDS+=" uid gid sid "
CMDS+=" groupname sessionid shells"
CMDS+=" userents groupents "

LOCPROG=macuser.x
TDIRS=" /usr/local /opt/local "

function linkdir {
  typeset TDIR=${1}
  for C in ${CMDS} ; do
    ln -f ${LOCPROG} ${TDIR}/bin/${C}
  done
}

if [[ -x "${LOCPROG}" ]] ; then
  for D in ${TDIRS} ; do
    if [[ -d "${D}" ]] ; then
      linkdir $D
    else
      print -u 2 -- "target directory not present"
      break ;
    fi
  done
else
  print -u 2 -- "program not made"
fi


