#!/usr/extra/bin/ksh
# INSTALL-DAM


: ${HOME:=$( userhome )}
: ${EXTRA:=/usr/extra}
: ${USRLCOAL:=/usr/local}

ma all

LIBS="libu.o libu.so libu.dylib"

TDIRS+=" ${HOME}/github/system/lib"
TDIRS+=" ${HOME}/github/other/lib"
TDIRS+=" ${HOME}/lib "
TDIRS+=" ${EXTRA}/lib "
TDIRS+=" ${USRLOCAL}/lib "

if [[ libu.so -ef libu.dylib ]] ; then
  print EQUAL
else
  print LN
  ln -f libu.so libu.dylib
fi

for LIB in ${LIBS} ; do
  if [[ -r "${LIB}" ]] ; then
    for TD in ${TDIRS} ; do
      if [[ -d "${TD}" ]] ; then
        M=0664
	if [[ ${LIB} == *.so ]] ; then
	  M=0775
        fi
        lnx ${LIB} ${TD}
      fi
    done
  fi
done

