'\"
.TH cb 1 "24 July 1995" LOCAL
.SH NAME
cb \- C program beautifier
.SH SYNOPSIS
.\"_
.if n .pH g1.cb @(#)cb	40.10 of 10/10/89
.\" Copyright 1989 AT&T
.nr X
.if \nX=0 .ds x} cb 1 "Advanced C Utilities" "\&"
.if \nX=1 .ds x} cb 1 "Advanced C Utilities"
.if \nX=2 .ds x} cb 1 "" "\&"
.if \nX=3 .ds x} cb "" "" "\&"
.\"_
\f4cb [\-s] [\-j] [\-l \f2leng\f4] [\-V] [\f2file  ...\f4]\f1
.SH DESCRIPTION
The
\f4cb\fP
command reads syntactically correct C programs
either from its arguments or from the standard input,
and writes them on the standard output with spacing and indentation
that display the structure of the C code.
By default,
\f4cb\fP
preserves all user new-lines.
.ds ]W
.PP
\f4cb\fP
accepts the following options.
.TP 12
\f4\-s\f1
Write the code in the style of
Kernighan and Ritchie found in
.IR "The C Programming Language" .
.TP 12
\f4\-j\f1
Put split lines back together.
.TP 12
\f4\-l \f2leng\f1
Split lines that are longer than
.IR leng .
.TP 12
\f4\-V\f1
Print on standard error output the version of 
\f4cb\fP
invoked.
.SH "NOTES"
\f4cb\fP
treats \f4asm\fP as a keyword.
.PP
The format of structure initializations is unchanged by
\f4cb\fP.
.P
Punctuation that is hidden in
preprocessing directives causes indentation errors.
.SH "SEE ALSO"
.\".BR acc (1)
.\"(\f2Solaris 1.x only\f1),
.BR cc (1)
(\f2Solaris 2.x only\f1)
.br
Kernighan, B. W., and Ritchie, D. M.,
.IR "The C Programming Language",
Second Edition, Prentice-Hall, 1988.
.\"	@(#)cb.1	6.2 of 9/2/83
.\".Ee
