#!/usr/extra/bin/ksh
# CHANGER

NAMES=
NAMES="${NAMES} connection_sockpeername"


DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
    for N in ${NAMES} ; do
      if fgrep "${N}" $F > ${DN} ; then
      ed - $F <<\EOF
g/connection_sockpeername/s//connection_sockremname/g
	w
	q
EOF
      fi
    done
  fi
done


