#!/usr/extra/bin/ksh
# HAVECC

: ${TMPDIR:=/tmp}
TF=${TMPDIR}/havecc${$}
for N in "${@}" ; do
  if [[ -n "${N}" ]] ; then
    files_c | fgr "${N}c" > ${TF}
    if [[ -s "${TF}" ]] ; then
      print -- YES
      rm -f ${N}
    fi
  fi
done
rm -f "${TF}"

