#!/usr/extra/bin/ksh
# MKCHANGES

DN=/dev/null

for F in "${@}" ; do
  if [[ -r "${F}" ]] ; then
      if fgrep -f search.txt $F > ${DN} ; then
      ed - $F <<\EOF
g/limits.h/s//climits/g
g/errno.h/s//cerrno/g
g/signal.h/s//csignal/g
g/stddef.h/s//cstddef/g
g/stdlib.h/s//cstdlib/g
g/stdio.h/s//cstdio/g
g/stdarg.h/s//cstdarg/g
g/string.h/s//cstring/g
	w
	q
EOF
      fi
  fi
done


